<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Surplus.Testing</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\surplus.Domain\surplus.Domain.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\surplus.Domain\SharedKernel\StrongIds\StrongIds.GlobalUsings.cs">
      <Link>StrongIds.GlobalUsings.cs</Link>
    </Compile>
  </ItemGroup>

</Project>
